name: Terraform Plan

on:
    pull_request:
        branches:
            - master

env:
    TF_VERSION: 1.7.5

jobs:
    terraform_paln:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              uses: ./.github/plan
              with:
                terraform_directory: 'terraform'
                tf_version: ${{ env.TF_VERSION }}
                ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
                ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}