name: 'Terraform setup and plan'
description: 'Setup Terraform and run terraform plan'
inputs:
  terraform_directory:
    description: 'The directory containing the Terraform configuration'
    required: true
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: '1.7.5'
  AZURE_CREDENTIALS:
    description: 'Azure Service Principal Credentials'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Auth to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Terraform init
      working-directory: ${{ github.workspace }}/${{ inputs.terraform_directory }}
      shell: bash
      run: | 
        terraform init 

    - name: Terraform plan
      working-directory: ${{ github.workspace }}/${{ inputs.terraform_directory }}
      shell: bash
      run: | 
        terraform plan