name: 'Terraform setup and plan'
description: 'Setup Terraform and run terraform plan'
inputs:
  terraform_directory:
    description: 'The directory containing the Terraform configuration'
    required: true
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: '1.7.5'
  ARM_CLIENT_ID:
    description: 'Azure Service Principal Client ID'
    required: true
  ARM_CLIENT_SECRET:
    description: 'Azure Service Principal Client Secret'
    required: true
  ARM_SUBSCRIPTION_ID:
    description: 'Azure Subscription ID'
    required: true
  ARM_TENANT_ID:
    description: 'Azure Tenant ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Auth to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        client-secret: ${{ inputs.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}

    - name: Terraform init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: | 
        terraform init 

    - name: Terraform plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: | 
        terraform plan