name: AKS Infrastructure Deployment

on:
    pull_request:
        branches:
            - master
    
    workflow_dispatch:

env:
    TF_VERSION: 1.7.5

jobs:
    terraform_paln:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        steps:
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              uses: ./.github/plan/aks
              with:
                terraform_directory: 'terraform/aks'
                terraform_version: ${{ env.TF_VERSION }}
                AZURE_CREDENTIALS : ${{ secrets.AZURE_CREDENTIALS }}
